### ISSUE TITLE
Integration 'linky' not found

### ISSUE THREAD

**Issue by agryson** [cyprieng/linky-home-assistant#5]
I have set up my config as documented but am getting the following error when I check my `.yaml` config in developer tools:

> Platform error sensor.linky - Integration 'linky' not found.

I checked the full logs and saw this:
`2023-03-15 09:01:19.088 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'linky' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

Which is probably the issue. Any help appreciated.

Further details included for completeness.

## Background
Installed using HACS by adding `cyprieng/linky-home-assistant` as a custom repository, installing and restarting.

It showed up and appears installed:
![image](https://user-images.githubusercontent.com/1445853/225249227-1b6447c0-0056-4394-a0dc-dd0834250803.png)

I've got a few different sensors, so have split out my sensors to a different yaml like so:
``` yaml
# configuration.yaml
sensor: !include sensors.yaml
```
``` yaml
# sensors.yaml
# ... some other sensors that are working fine ...

  - platform: linky
    api_key: !secret linky_api_key
    point_id: !secret linky_point_id
    cost: 0.1557  # Cost per kWh
```

The `api_key` and `point_id` have been split out to the `secrets.yaml` file as is best practice but I don't think we're even getting that far - the issue seems to be that the platform `linky` is not recognized...

## Useful Info
Home Assistant Version: 2023.3.3
Home Assistant Frontend Version: 20230309.0
Running in Docker
